/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Mike Shogin",
  "tagline": "System Analyst & IT Consultant",
  "favicon": "img/favicon.ico",
  "url": "https://mikeshogin.com",
  "baseUrl": "/ru/",
  "organizationName": "mikeshogin",
  "projectName": "mikeshogin.github.io",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "ru"
    ],
    "localeConfigs": {
      "en": {
        "label": "English",
        "direction": "ltr",
        "htmlLang": "en-US"
      },
      "ru": {
        "label": "Русский",
        "direction": "ltr",
        "htmlLang": "ru-RU"
      }
    },
    "path": "i18n"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "editUrl": "https://github.com/mikeshogin/mikeshogin.github.io/tree/main/"
        },
        "blog": {
          "showReadingTime": true,
          "blogTitle": "Blog",
          "blogDescription": "Insights on system analysis, architecture, and IT consulting",
          "postsPerPage": 8,
          "blogSidebarTitle": "Recent posts",
          "blogSidebarCount": 5,
          "feedOptions": {
            "type": "all",
            "copyright": "Copyright © 2025 Mike Shogin."
          }
        },
        "pages": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Майк Шогин",
      "logo": {
        "alt": "Mike Shogin Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/about",
          "position": "left",
          "label": "Обо мне"
        },
        {
          "to": "/services",
          "position": "left",
          "label": "Услуги"
        },
        {
          "to": "/portfolio",
          "position": "left",
          "label": "Портфолио"
        },
        {
          "to": "/blog",
          "label": "Блог",
          "position": "left"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "href": "https://github.com/mikeshogin",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Услуги",
          "items": [
            {
              "label": "Системный анализ",
              "to": "/services/system-analysis"
            },
            {
              "label": "Менторство и коучинг",
              "to": "/services/mentorship"
            },
            {
              "label": "IT-консалтинг",
              "to": "/services/consulting"
            },
            {
              "label": "Аудит архитектуры",
              "to": "/services/architecture-audit"
            }
          ]
        },
        {
          "title": "Ресурсы",
          "items": [
            {
              "label": "Блог",
              "to": "/blog"
            },
            {
              "label": "Портфолио",
              "to": "/portfolio"
            },
            {
              "label": "Обо мне",
              "to": "/about"
            }
          ]
        },
        {
          "title": "Связаться",
          "items": [
            {
              "label": "LinkedIn",
              "href": "https://linkedin.com/in/mikeshogin"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/mikeshogin"
            },
            {
              "label": "Электронная почта",
              "href": "mailto:contact@mikeshogin.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 Майк Шогин. Создано с помощью Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "system analysis, IT consulting, architecture audit, mentorship, software development, tech lead"
      },
      {
        "name": "description",
        "content": "Professional system analyst and IT consultant offering expertise in system analysis, architecture audits, and technical mentorship."
      }
    ],
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
